# Generated by Django 3.2.7 on 2021-09-24 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture', models.TextField(default='india-pakistan')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('bet_description', models.TextField(default='India win')),
                ('bet_result', models.IntegerField(blank=True, choices=[(0, 'LOST'), (1, 'WON'), (2, 'PENDING')], default=2)),
            ],
        ),
    ]
