# Generated by Django 3.2.7 on 2021-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlebet',
            name='bet_description',
            field=models.CharField(default='India win', max_length=74),
        ),
        migrations.AlterField(
            model_name='singlebet',
            name='fixture',
            field=models.CharField(default='india-pakistan', max_length=124),
        ),
    ]
