# Generated by Django 3.2.7 on 2021-09-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0002_auto_20210924_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlebet',
            name='bet_description',
            field=models.CharField(default='Awayteam win / Draw', max_length=74),
        ),
        migrations.AlterField(
            model_name='singlebet',
            name='fixture',
            field=models.CharField(default='Hometeam-Awayteam', max_length=124),
        ),
    ]
