# Generated by Django 3.2.7 on 2021-09-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0003_auto_20210924_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlebet',
            name='odds',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
