# Generated by Django 3.2.7 on 2021-09-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0004_singlebet_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlebet',
            name='fixture',
            field=models.CharField(default='Hometeam-Awayteam', max_length=224),
        ),
    ]
