# Generated by Django 3.2.7 on 2021-09-29 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0005_alter_singlebet_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlebet',
            name='odds',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, validators=[django.core.validators.MaxValueValidator(150)]),
        ),
    ]
