# Generated by Django 3.2.7 on 2021-09-29 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0006_alter_singlebet_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlebet',
            name='odds',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, validators=[django.core.validators.MaxValueValidator(150, message='Sorry! Odds less than 150 is allowed')]),
        ),
    ]
