# Generated by Django 3.2.7 on 2021-09-29 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0008_alter_singlebet_odds'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture', models.CharField(default='Hometeam-Awayteam', max_length=500)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('odds', models.DecimalField(decimal_places=3, default=0.0, max_digits=8, validators=[django.core.validators.MaxValueValidator(150, message='Sorry! Odds less than 150 is allowed')])),
                ('bet_description', models.CharField(default='Awayteam win / Draw', max_length=200)),
                ('bet_result', models.IntegerField(blank=True, choices=[(0, 'LOST'), (1, 'WON'), (2, 'PENDING')], default=2)),
            ],
        ),
    ]
